version: '2'

services:
  collectd:
    # build:
    #  context:  ./build/collectd
    image: ermlab/collectd
    privileged: true
    network_mode: host
    volumes:
      - /proc:/mnt/proc:ro
      - ./collectd.conf:/etc/collectd/collectd.conf
      - ./types.db:/usr/share/collectd/types.db
      - /var/run/docker.sock:/var/run/docker.sock
  influxdb:
    image: influxdb:1.0
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
    volumes:
      - /var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db:ro
  grafana:
    image: grafana/grafana:3.1.1
    ports:
      - "4000:3000"
    volumes:
      - /var/lib/grafana
